[package]
name = "nacs-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dav-server = "0.11.0"
libp2p = "0.56.0"
rusqlite = "0.40.1"
tokio = { version = "1.52.3", features = ["full"] }
hyper = { version = "1.10.1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
